name = "QCodeDiscovery"
uuid = "e65589a1-6be8-4a17-a56b-9b9c76ae45cd"
authors = ["qldpc-discovery contributors"]
version = "0.1.0"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
